version: '3.8'

services:
  front-end-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    environment:
      - NODE_ENV=development
    command: npm start